### ISSUE TITLE
insert error

### ISSUE THREAD

**Issue by Guillaume-favier** [na2axl/jsondb-js#2]
I just want to do an insert and this append
```
(node:16980) UnhandledPromiseRejectionWarning: TypeError: value.replace is not a function
    at QueryParser.quote (C:\Users\favie\Documents\programation\testgenshin\node_modules\jsondb-js\src\QueryParser.js:70:23)
    at Function.JSONDB.quote (C:\Users\favie\Documents\programation\testgenshin\node_modules\jsondb-js\src\JSONDB.js:293:49)
    at addPlayer (C:\Users\favie\Documents\programation\testgenshin\index.js:74:18)
    at main (C:\Users\favie\Documents\programation\testgenshin\index.js:91:10)
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by Guillaume-favier** [comment]
it's because the function QueryParser.prototype.quote assume that the parametter is a string
